/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author odavid
 */
public class FormularioCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioCliente
     */
    public FormularioCliente() {
  
        initComponents();
        ((BasicInternalFrameUI)super.getUI()).setNorthPane(null);
        super.setBorder(null);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jButtonCerrar = new javax.swing.JButton();
        jTextFieldIdCliente = new javax.swing.JTextField();
        jButtonGuardarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 575));
        setMinimumSize(new java.awt.Dimension(400, 575));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(400, 575));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(8, 8, 50));
        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 246, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLIENTES");
        jLabel1.setMaximumSize(new java.awt.Dimension(244, 19));
        jLabel1.setMinimumSize(new java.awt.Dimension(244, 19));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 19));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 80));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel3.setText("Telefono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel4.setText("Apellido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel5.setText("Nombre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel6.setText("Identificacion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jTextFieldIdentificacion.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldIdentificacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 1, 2));
        getContentPane().add(jTextFieldIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 320, 37));

        jTextFieldNombre.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 320, 37));

        jTextFieldTelefono.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldTelefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        getContentPane().add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 322, 37));

        jTextFieldApellido.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        getContentPane().add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 320, 37));

        jButtonCerrar.setBackground(new java.awt.Color(130, 46, 17));
        jButtonCerrar.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonCerrar.setFocusable(false);
        getContentPane().add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 80, 40));
        getContentPane().add(jTextFieldIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jButtonGuardarCliente.setBackground(new java.awt.Color(8, 165, 155));
        jButtonGuardarCliente.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonGuardarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardarCliente.setText("Guardar");
        jButtonGuardarCliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonGuardarCliente.setFocusable(false);
        getContentPane().add(jButtonGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonGuardarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldIdCliente;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables


    public javax.swing.JButton getjButtonCerrar() {
        return jButtonCerrar;
    }

    public void setjButtonCerrar(javax.swing.JButton jButtonCerrar) {
        this.jButtonCerrar = jButtonCerrar;
    }

    public javax.swing.JButton getjButtonGuardarCliente() {
        return jButtonGuardarCliente;
    }

    public void setjButtonGuardarCliente(javax.swing.JButton jButtonGuardarCliente) {
        this.jButtonGuardarCliente = jButtonGuardarCliente;
    }

    public javax.swing.JTextField getjTextFieldApellido() {
        return jTextFieldApellido;
    }

    public void setjTextFieldApellido(javax.swing.JTextField jTextFieldApellido) {
        this.jTextFieldApellido = jTextFieldApellido;
    }

    public javax.swing.JTextField getjTextFieldIdCliente() {
        return jTextFieldIdCliente;
    }

    public void setjTextFieldIdCliente(javax.swing.JTextField jTextFieldIdCliente) {
        this.jTextFieldIdCliente = jTextFieldIdCliente;
    }

    public javax.swing.JTextField getjTextFieldIdentificacion() {
        return jTextFieldIdentificacion;
    }

    public void setjTextFieldIdentificacion(javax.swing.JTextField jTextFieldIdentificacion) {
        this.jTextFieldIdentificacion = jTextFieldIdentificacion;
    }

    public javax.swing.JTextField getjTextFieldNombre() {
        return jTextFieldNombre;
    }

    public void setjTextFieldNombre(javax.swing.JTextField jTextFieldNombre) {
        this.jTextFieldNombre = jTextFieldNombre;
    }

    public javax.swing.JTextField getjTextFieldTelefono() {
        return jTextFieldTelefono;
    }

    public void setjTextFieldTelefono(javax.swing.JTextField jTextFieldTelefono) {
        this.jTextFieldTelefono = jTextFieldTelefono;
    }
}
