/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author odavid
 */
public class FormularioVehiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioCliente
     */
    public FormularioVehiculo() {
  
        initComponents();
        ((BasicInternalFrameUI)super.getUI()).setNorthPane(null);
        super.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextFieldPlaca = new javax.swing.JTextField();
        jTextFieldKilometraje = new javax.swing.JTextField();
        jButtonCerrar = new javax.swing.JButton();
        jTextFieldIdVehiculo = new javax.swing.JTextField();
        jButtonGuardarVehiculo = new javax.swing.JButton();
        jRadioButtonTipoCamioneta = new javax.swing.JRadioButton();
        jRadioButtonTipoAuto = new javax.swing.JRadioButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 575));
        setMinimumSize(new java.awt.Dimension(400, 575));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(400, 575));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(8, 8, 50));
        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 246, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VEHICULO");
        jLabel1.setMaximumSize(new java.awt.Dimension(244, 19));
        jLabel1.setMinimumSize(new java.awt.Dimension(244, 19));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 19));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 80));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel4.setText("Kilometraje");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel5.setText("Placa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel6.setText("Descripcion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jTextFieldDescripcion.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldDescripcion.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 1, 2));
        getContentPane().add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 322, 37));

        jTextFieldPlaca.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldPlaca.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        getContentPane().add(jTextFieldPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 322, 37));

        jTextFieldKilometraje.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldKilometraje.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        getContentPane().add(jTextFieldKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 322, 37));

        jButtonCerrar.setBackground(new java.awt.Color(130, 46, 17));
        jButtonCerrar.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonCerrar.setFocusable(false);
        getContentPane().add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 80, 40));
        getContentPane().add(jTextFieldIdVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jButtonGuardarVehiculo.setBackground(new java.awt.Color(8, 165, 155));
        jButtonGuardarVehiculo.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonGuardarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardarVehiculo.setText("Guardar");
        jButtonGuardarVehiculo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonGuardarVehiculo.setFocusable(false);
        getContentPane().add(jButtonGuardarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 80, 40));

        jRadioButtonTipoCamioneta.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jRadioButtonTipoCamioneta.setSelected(true);
        jRadioButtonTipoCamioneta.setText("Camioneta");
        jRadioButtonTipoCamioneta.setOpaque(true);
        getContentPane().add(jRadioButtonTipoCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 120, -1));

        jRadioButtonTipoAuto.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jRadioButtonTipoAuto.setText("Auto");
        jRadioButtonTipoAuto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jRadioButtonTipoAuto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jRadioButtonTipoAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonGuardarVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButtonTipoAuto;
    private javax.swing.JRadioButton jRadioButtonTipoCamioneta;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldIdVehiculo;
    private javax.swing.JTextField jTextFieldKilometraje;
    private javax.swing.JTextField jTextFieldPlaca;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getjButtonCerrar() {
        return jButtonCerrar;
    }

    public void setjButtonCerrar(javax.swing.JButton jButtonCerrar) {
        this.jButtonCerrar = jButtonCerrar;
    }

    public javax.swing.JButton getjButtonGuardarVehiculo() {
        return jButtonGuardarVehiculo;
    }

    public void setjButtonGuardarVehiculo(javax.swing.JButton jButtonGuardarVehiculo) {
        this.jButtonGuardarVehiculo = jButtonGuardarVehiculo;
    }

    public javax.swing.JRadioButton getjRadioButtonTipoAuto() {
        return jRadioButtonTipoAuto;
    }

    public void setjRadioButtonTipoAuto(javax.swing.JRadioButton jRadioButtonTipoAuto) {
        this.jRadioButtonTipoAuto = jRadioButtonTipoAuto;
    }

    public javax.swing.JRadioButton getjRadioButtonTipoCamioneta() {
        return jRadioButtonTipoCamioneta;
    }

    public void setjRadioButtonTipoCamioneta(javax.swing.JRadioButton jRadioButtonTipoCamioneta) {
        this.jRadioButtonTipoCamioneta = jRadioButtonTipoCamioneta;
    }

    public javax.swing.JTextField getjTextFieldDescripcion() {
        return jTextFieldDescripcion;
    }

    public void setjTextFieldDescripcion(javax.swing.JTextField jTextFieldDescripcion) {
        this.jTextFieldDescripcion = jTextFieldDescripcion;
    }

    public javax.swing.JTextField getjTextFieldIdVehiculo() {
        return jTextFieldIdVehiculo;
    }

    public void setjTextFieldIdVehiculo(javax.swing.JTextField jTextFieldIdVehiculo) {
        this.jTextFieldIdVehiculo = jTextFieldIdVehiculo;
    }

    public javax.swing.JTextField getjTextFieldKilometraje() {
        return jTextFieldKilometraje;
    }

    public void setjTextFieldKilometraje(javax.swing.JTextField jTextFieldKilometraje) {
        this.jTextFieldKilometraje = jTextFieldKilometraje;
    }

    public javax.swing.JTextField getjTextFieldPlaca() {
        return jTextFieldPlaca;
    }

    public void setjTextFieldPlaca(javax.swing.JTextField jTextFieldPlaca) {
        this.jTextFieldPlaca = jTextFieldPlaca;
    }


}
