/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author odavid
 */
public class VistaListaVehiculos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioCliente
     */
    public VistaListaVehiculos() {
  
        initComponents();
        ((BasicInternalFrameUI)super.getUI()).setNorthPane(null);
        super.setBorder(null);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonEliminarVehiculo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaVehiculos = new javax.swing.JTable();
        jTextFieldCantVehiculosDis = new javax.swing.JTextField();
        jTextFieldCantVehiculosAl = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButtonNuevoVehiculo = new javax.swing.JButton();
        jButtonEditarVehiculo = new javax.swing.JButton();
        jButtonEntregado = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jTextFieldEstatus = new javax.swing.JTextField();
        jButtonVisualizarAlquiler = new javax.swing.JButton();
        jTextFieldPorRecibo = new javax.swing.JTextField();
        jTextFieldPorDescr = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonBuscarPor = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setMaximumSize(new java.awt.Dimension(1197, 615));
        setMinimumSize(new java.awt.Dimension(1197, 615));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1197, 615));
        setRequestFocusEnabled(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(8, 8, 50));
        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 246, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VEHICULOS REGISTRADOS");
        jLabel1.setMaximumSize(new java.awt.Dimension(244, 19));
        jLabel1.setMinimumSize(new java.awt.Dimension(244, 19));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 19));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 70));

        jButtonEliminarVehiculo.setBackground(new java.awt.Color(130, 46, 17));
        jButtonEliminarVehiculo.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonEliminarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminarVehiculo.setText("Eliminar");
        jButtonEliminarVehiculo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonEliminarVehiculo.setFocusable(false);
        getContentPane().add(jButtonEliminarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 80, 130, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.lightGray), "LISTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 17))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableListaVehiculos.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jTableListaVehiculos.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jTableListaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NO.", "TIPO DE VEHICULO", "DESCRIPCION ", "PLACAS", "KILOMETRAJE", "STATUS", "RECIBOS ASOCIADOS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaVehiculos.setMaximumSize(new java.awt.Dimension(90, 0));
        jTableListaVehiculos.setShowHorizontalLines(false);
        jTableListaVehiculos.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTableListaVehiculos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1160, 230));

        jTextFieldCantVehiculosDis.setEditable(false);
        jTextFieldCantVehiculosDis.setBackground(new java.awt.Color(254, 254, 254));
        jTextFieldCantVehiculosDis.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldCantVehiculosDis.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        jPanel1.add(jTextFieldCantVehiculosDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 190, 37));

        jTextFieldCantVehiculosAl.setEditable(false);
        jTextFieldCantVehiculosAl.setBackground(new java.awt.Color(254, 254, 254));
        jTextFieldCantVehiculosAl.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldCantVehiculosAl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        jPanel1.add(jTextFieldCantVehiculosAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 280, 190, 37));

        jLabel16.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel16.setText("VEHICULOS ALQUILADOS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, -1, -1));

        jLabel14.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel14.setText("VEHICULOS DISPONIBLES");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1180, 440));

        jButtonNuevoVehiculo.setBackground(new java.awt.Color(8, 165, 155));
        jButtonNuevoVehiculo.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonNuevoVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNuevoVehiculo.setText("Nuevo");
        jButtonNuevoVehiculo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonNuevoVehiculo.setFocusable(false);
        getContentPane().add(jButtonNuevoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 130, 40));

        jButtonEditarVehiculo.setBackground(new java.awt.Color(8, 165, 155));
        jButtonEditarVehiculo.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonEditarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarVehiculo.setText("Editar");
        jButtonEditarVehiculo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonEditarVehiculo.setFocusable(false);
        getContentPane().add(jButtonEditarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 120, 40));

        jButtonEntregado.setBackground(new java.awt.Color(8, 165, 155));
        jButtonEntregado.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonEntregado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntregado.setText("Confirmar de Entregado");
        jButtonEntregado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonEntregado.setFocusable(false);
        getContentPane().add(jButtonEntregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 260, 40));

        jButtonLimpiar.setBackground(new java.awt.Color(8, 165, 155));
        jButtonLimpiar.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonLimpiar.setFocusable(false);
        getContentPane().add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 40));

        jTextFieldEstatus.setBackground(new java.awt.Color(254, 254, 254));
        jTextFieldEstatus.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldEstatus.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        getContentPane().add(jTextFieldEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 90, 37));

        jButtonVisualizarAlquiler.setBackground(new java.awt.Color(8, 165, 155));
        jButtonVisualizarAlquiler.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonVisualizarAlquiler.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVisualizarAlquiler.setText("Visualizar Alquiler");
        jButtonVisualizarAlquiler.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonVisualizarAlquiler.setFocusable(false);
        getContentPane().add(jButtonVisualizarAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 130, 40));

        jTextFieldPorRecibo.setBackground(new java.awt.Color(254, 254, 254));
        jTextFieldPorRecibo.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldPorRecibo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        getContentPane().add(jTextFieldPorRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 90, 37));

        jTextFieldPorDescr.setBackground(new java.awt.Color(254, 254, 254));
        jTextFieldPorDescr.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldPorDescr.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        getContentPane().add(jTextFieldPorDescr, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 90, 37));

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel13.setText("Estatus");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jLabel15.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel15.setText("Recibo");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jButtonBuscarPor.setBackground(new java.awt.Color(8, 165, 155));
        jButtonBuscarPor.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonBuscarPor.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscarPor.setText("Buscar Por");
        jButtonBuscarPor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonBuscarPor.setFocusable(false);
        getContentPane().add(jButtonBuscarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 40));

        jLabel18.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel18.setText("Descripcion");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarPor;
    private javax.swing.JButton jButtonEditarVehiculo;
    private javax.swing.JButton jButtonEliminarVehiculo;
    private javax.swing.JButton jButtonEntregado;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonNuevoVehiculo;
    private javax.swing.JButton jButtonVisualizarAlquiler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaVehiculos;
    private javax.swing.JTextField jTextFieldCantVehiculosAl;
    private javax.swing.JTextField jTextFieldCantVehiculosDis;
    private javax.swing.JTextField jTextFieldEstatus;
    private javax.swing.JTextField jTextFieldPorDescr;
    private javax.swing.JTextField jTextFieldPorRecibo;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getjButtonEditarVehiculo() {
        return jButtonEditarVehiculo;
    }

    public void setjButtonEditarVehiculo(javax.swing.JButton jButtonEditarVehiculo) {
        this.jButtonEditarVehiculo = jButtonEditarVehiculo;
    }

    public javax.swing.JButton getjButtonEliminarVehiculo() {
        return jButtonEliminarVehiculo;
    }

    public void setjButtonEliminarVehiculo(javax.swing.JButton jButtonEliminarVehiculo) {
        this.jButtonEliminarVehiculo = jButtonEliminarVehiculo;
    }

    public javax.swing.JButton getjButtonNuevoVehiculo() {
        return jButtonNuevoVehiculo;
    }

    public void setjButtonNuevoVehiculo(javax.swing.JButton jButtonNuevoVehiculo) {
        this.jButtonNuevoVehiculo = jButtonNuevoVehiculo;
    }

    public javax.swing.JTextField getjTextFieldCantVehiculosAl() {
        return jTextFieldCantVehiculosAl;
    }

    public void setjTextFieldCantVehiculosAl(javax.swing.JTextField jTextFieldCantVehiculosAl) {
        this.jTextFieldCantVehiculosAl = jTextFieldCantVehiculosAl;
    }

    public javax.swing.JTextField getjTextFieldCantVehiculosDis() {
        return jTextFieldCantVehiculosDis;
    }

    public void setjTextFieldCantVehiculosDis(javax.swing.JTextField jTextFieldCantVehiculosDis) {
        this.jTextFieldCantVehiculosDis = jTextFieldCantVehiculosDis;
    }

    public javax.swing.JTable getjTableListaVehiculos() {
        return jTableListaVehiculos;
    }

    public void setjTableListaVehiculos(javax.swing.JTable jTableListaVehiculos) {
        this.jTableListaVehiculos = jTableListaVehiculos;
    }

    public JButton getjButtonEntregado() {
        return jButtonEntregado;
    }

    public JButton getjButtonBuscarPor() {
        return jButtonBuscarPor;
    }

    public void setjButtonBuscarPor(JButton jButtonBuscarPor) {
        this.jButtonBuscarPor = jButtonBuscarPor;
    }

    public JTextField getjTextFieldEstatus() {
        return jTextFieldEstatus;
    }

    public void setjTextFieldEstatus(JTextField jTextFieldEstatus) {
        this.jTextFieldEstatus = jTextFieldEstatus;
    }

    public JTextField getjTextFieldPorDescr() {
        return jTextFieldPorDescr;
    }

    public void setjTextFieldPorDescr(JTextField jTextFieldPorDescr) {
        this.jTextFieldPorDescr = jTextFieldPorDescr;
    }

    public JTextField getjTextFieldPorRecibo() {
        return jTextFieldPorRecibo;
    }

    public void setjTextFieldPorRecibo(JTextField jTextFieldPorRecibo) {
        this.jTextFieldPorRecibo = jTextFieldPorRecibo;
    }
    
    
}
