/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author odavid
 */
public class VistaListaAlquiler extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioCliente
     */
    public VistaListaAlquiler() {
  
        initComponents();
        ((BasicInternalFrameUI)super.getUI()).setNorthPane(null);
        super.setBorder(null);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaAlquiler = new javax.swing.JTable();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNombre2 = new javax.swing.JTextField();
        jButtonGuardarCliente2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setMaximumSize(new java.awt.Dimension(1197, 615));
        setMinimumSize(new java.awt.Dimension(1197, 615));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1197, 615));
        setRequestFocusEnabled(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(8, 8, 50));
        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 246, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALQUILERES REGISTRADOS");
        jLabel1.setMaximumSize(new java.awt.Dimension(244, 19));
        jLabel1.setMinimumSize(new java.awt.Dimension(244, 19));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 19));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 70));

        jButtonCerrar.setBackground(new java.awt.Color(130, 46, 17));
        jButtonCerrar.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonCerrar.setFocusable(false);
        getContentPane().add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 110, 130, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.lightGray), "Detalle Alquiler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 17))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableListaAlquiler.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jTableListaAlquiler.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jTableListaAlquiler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RECIBO", "CLIENTE", "VEHICULO", "DESCRIPCION ", "DIAS ALQUILADOS", "VALOR DE ALQUILER", "SEGURO", "FECHA ENTREGA", "HORA ENTREGA", "FECHA DEVUELTA", "HORA DEVUELTA", "TOTAL A PAGAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaAlquiler.setMaximumSize(new java.awt.Dimension(90, 0));
        jTableListaAlquiler.setShowHorizontalLines(false);
        jTableListaAlquiler.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTableListaAlquiler);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1160, 230));

        jTextFieldNombre1.setEditable(false);
        jTextFieldNombre1.setBackground(new java.awt.Color(254, 254, 254));
        jTextFieldNombre1.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldNombre1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        jPanel1.add(jTextFieldNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 190, 37));

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel13.setText("Total Recaudo");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, -1, -1));

        jLabel15.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel15.setText("Total Seguro");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, -1, -1));

        jTextFieldNombre2.setEditable(false);
        jTextFieldNombre2.setBackground(new java.awt.Color(254, 254, 254));
        jTextFieldNombre2.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jTextFieldNombre2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        jPanel1.add(jTextFieldNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 290, 190, 37));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1180, 440));

        jButtonGuardarCliente2.setBackground(new java.awt.Color(8, 165, 155));
        jButtonGuardarCliente2.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonGuardarCliente2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardarCliente2.setText("Guardar");
        jButtonGuardarCliente2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonGuardarCliente2.setFocusable(false);
        getContentPane().add(jButtonGuardarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonGuardarCliente2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaAlquiler;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldNombre2;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonCerrar() {
        return jButtonCerrar;
    }

    public void setjButtonCerrar(JButton jButtonCerrar) {
        this.jButtonCerrar = jButtonCerrar;
    }

    public JTable getjTableListaAlquiler() {
        return jTableListaAlquiler;
    }

    public void setjTableListaAlquiler(JTable jTableListaAlquiler) {
        this.jTableListaAlquiler = jTableListaAlquiler;
    }


}


