/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;

/**
 *
 * @author odavid
 */
public class VistaListaVehiculosJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListaVehiculosJPanelView
     */
    public VistaListaVehiculosJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDetalleVehiculo = new javax.swing.JTable();
        jButtonAgregarVehiculo = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Vehiculos Registrados Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 20))); // NOI18N

        jTableDetalleVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Descripcion", "Kilometraje", "Placa", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDetalleVehiculo.setInheritsPopupMenu(true);
        jTableDetalleVehiculo.setShowHorizontalLines(false);
        jTableDetalleVehiculo.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTableDetalleVehiculo);

        jButtonAgregarVehiculo.setBackground(new java.awt.Color(8, 165, 155));
        jButtonAgregarVehiculo.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonAgregarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarVehiculo.setText("AGREGAR");
        jButtonAgregarVehiculo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonAgregarVehiculo.setFocusable(false);

        jButtonCerrar.setBackground(new java.awt.Color(130, 46, 17));
        jButtonCerrar.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        jButtonCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCerrar.setText("CERRAR");
        jButtonCerrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonCerrar.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonAgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarVehiculo;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDetalleVehiculo;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getjTableDetalleVehiculo() {
        return jTableDetalleVehiculo;
    }

    public JButton getjButtonAgregarVehiculo() {
        return jButtonAgregarVehiculo;
    }

    public void setjButtonAgregarVehiculo(JButton jButtonAgregarVehiculo) {
        this.jButtonAgregarVehiculo = jButtonAgregarVehiculo;
    }

    public JButton getjButtonCerrarVentanaListaV() {
        return jButtonCerrar;
    }

    public void setjButtonCerrarVentanaListaV(JButton jButtonCerrarVentanaListaV) {
        this.jButtonCerrar = jButtonCerrarVentanaListaV;
    }
    
    

}
