/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author david
 */
public class CalcView extends javax.swing.JFrame {

    /**
     * Creates new form CalcView
     */
    public CalcView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEcuacion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelFn = new javax.swing.JPanel();
        sSeno = new javax.swing.JButton();
        sCoseno = new javax.swing.JButton();
        sTangente = new javax.swing.JButton();
        sLogNatural = new javax.swing.JButton();
        sLog = new javax.swing.JButton();
        sInverso = new javax.swing.JButton();
        sExponencialX = new javax.swing.JButton();
        sElevacion2 = new javax.swing.JButton();
        sElevacionY = new javax.swing.JButton();
        sValorAbs = new javax.swing.JButton();
        sPI = new javax.swing.JButton();
        sExponencial = new javax.swing.JButton();
        sNotacion = new javax.swing.JButton();
        sRadianes = new javax.swing.JButton();
        sRaiz = new javax.swing.JButton();
        jPanelBasico = new javax.swing.JPanel();
        n7 = new javax.swing.JButton();
        n8 = new javax.swing.JButton();
        n9 = new javax.swing.JButton();
        n4 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        n6 = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        n1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        n0 = new javax.swing.JButton();
        sPunto = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        sParentesis = new javax.swing.JButton();
        sPorcentaje = new javax.swing.JButton();
        sDivision = new javax.swing.JButton();
        sMultiplicar = new javax.swing.JButton();
        sRestar = new javax.swing.JButton();
        sSumar = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAURA ZARATE - ALGORITMOS DE ECUACIONES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ecuacion");

        jTextFieldEcuacion.setName("jtEcuacion"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldEcuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEcuacion, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Resultado");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelFn.setName("jpFn"); // NOI18N

        sSeno.setText("sin");
        sSeno.setMaximumSize(new java.awt.Dimension(48, 32));
        sSeno.setMinimumSize(new java.awt.Dimension(48, 32));
        sSeno.setName("sin()"); // NOI18N
        sSeno.setPreferredSize(new java.awt.Dimension(48, 32));

        sCoseno.setText("cos");
        sCoseno.setMaximumSize(new java.awt.Dimension(48, 32));
        sCoseno.setMinimumSize(new java.awt.Dimension(48, 32));
        sCoseno.setName("cos()"); // NOI18N
        sCoseno.setPreferredSize(new java.awt.Dimension(48, 32));

        sTangente.setText("tan");
        sTangente.setMaximumSize(new java.awt.Dimension(48, 32));
        sTangente.setMinimumSize(new java.awt.Dimension(48, 32));
        sTangente.setName("tan"); // NOI18N
        sTangente.setPreferredSize(new java.awt.Dimension(48, 32));

        sLogNatural.setText("ln");
        sLogNatural.setMaximumSize(new java.awt.Dimension(48, 32));
        sLogNatural.setMinimumSize(new java.awt.Dimension(48, 32));
        sLogNatural.setName("ln"); // NOI18N
        sLogNatural.setPreferredSize(new java.awt.Dimension(48, 32));

        sLog.setText("log");
        sLog.setMaximumSize(new java.awt.Dimension(48, 32));
        sLog.setMinimumSize(new java.awt.Dimension(48, 32));
        sLog.setName("log"); // NOI18N
        sLog.setPreferredSize(new java.awt.Dimension(48, 32));

        sInverso.setText("1/x");
        sInverso.setMaximumSize(new java.awt.Dimension(48, 32));
        sInverso.setMinimumSize(new java.awt.Dimension(48, 32));
        sInverso.setName("1/"); // NOI18N
        sInverso.setPreferredSize(new java.awt.Dimension(48, 32));

        sExponencialX.setText("e^x");
        sExponencialX.setMaximumSize(new java.awt.Dimension(48, 32));
        sExponencialX.setMinimumSize(new java.awt.Dimension(48, 32));
        sExponencialX.setName("e^"); // NOI18N
        sExponencialX.setPreferredSize(new java.awt.Dimension(48, 32));

        sElevacion2.setText("X^2");
        sElevacion2.setMaximumSize(new java.awt.Dimension(48, 32));
        sElevacion2.setMinimumSize(new java.awt.Dimension(48, 32));
        sElevacion2.setName("x^2"); // NOI18N
        sElevacion2.setPreferredSize(new java.awt.Dimension(48, 32));

        sElevacionY.setText("X^y");
        sElevacionY.setMaximumSize(new java.awt.Dimension(48, 32));
        sElevacionY.setMinimumSize(new java.awt.Dimension(48, 32));
        sElevacionY.setName("x^"); // NOI18N
        sElevacionY.setPreferredSize(new java.awt.Dimension(48, 32));

        sValorAbs.setText("|x|");
        sValorAbs.setMaximumSize(new java.awt.Dimension(48, 32));
        sValorAbs.setMinimumSize(new java.awt.Dimension(48, 32));
        sValorAbs.setName("|x|"); // NOI18N
        sValorAbs.setPreferredSize(new java.awt.Dimension(48, 32));

        sPI.setText("π");
        sPI.setMaximumSize(new java.awt.Dimension(48, 32));
        sPI.setMinimumSize(new java.awt.Dimension(48, 32));
        sPI.setName("π"); // NOI18N
        sPI.setPreferredSize(new java.awt.Dimension(48, 32));

        sExponencial.setText("e");
        sExponencial.setMaximumSize(new java.awt.Dimension(48, 32));
        sExponencial.setMinimumSize(new java.awt.Dimension(48, 32));
        sExponencial.setName("e"); // NOI18N
        sExponencial.setPreferredSize(new java.awt.Dimension(48, 32));

        sNotacion.setText("10^x");
        sNotacion.setMaximumSize(new java.awt.Dimension(48, 32));
        sNotacion.setMinimumSize(new java.awt.Dimension(48, 32));
        sNotacion.setName("*10^"); // NOI18N
        sNotacion.setPreferredSize(new java.awt.Dimension(48, 32));

        sRadianes.setText("< -");
        sRadianes.setMaximumSize(new java.awt.Dimension(48, 32));
        sRadianes.setMinimumSize(new java.awt.Dimension(48, 32));
        sRadianes.setPreferredSize(new java.awt.Dimension(48, 32));

        sRaiz.setText("√");
        sRaiz.setMaximumSize(new java.awt.Dimension(48, 32));
        sRaiz.setMinimumSize(new java.awt.Dimension(48, 32));
        sRaiz.setName("√"); // NOI18N
        sRaiz.setPreferredSize(new java.awt.Dimension(48, 32));

        javax.swing.GroupLayout jPanelFnLayout = new javax.swing.GroupLayout(jPanelFn);
        jPanelFn.setLayout(jPanelFnLayout);
        jPanelFnLayout.setHorizontalGroup(
            jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFnLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFnLayout.createSequentialGroup()
                        .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sExponencialX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sLogNatural, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sSeno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sValorAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sCoseno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sElevacion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sPI, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFnLayout.createSequentialGroup()
                        .addComponent(sNotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sRadianes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sTangente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sInverso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sElevacionY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sExponencial, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelFnLayout.setVerticalGroup(
            jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFnLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sNotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sRadianes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sTangente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sSeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sCoseno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sInverso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sLogNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sElevacionY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sExponencialX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sElevacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sExponencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sValorAbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sElevacion2.getAccessibleContext().setAccessibleName("x^2");

        jPanelBasico.setName("jpBasico"); // NOI18N

        n7.setText("7");
        n7.setMaximumSize(new java.awt.Dimension(48, 32));
        n7.setMinimumSize(new java.awt.Dimension(48, 32));
        n7.setName("7"); // NOI18N
        n7.setPreferredSize(new java.awt.Dimension(48, 32));

        n8.setText("8");
        n8.setMaximumSize(new java.awt.Dimension(48, 32));
        n8.setMinimumSize(new java.awt.Dimension(48, 32));
        n8.setName("8"); // NOI18N
        n8.setPreferredSize(new java.awt.Dimension(48, 32));

        n9.setText("9");
        n9.setMaximumSize(new java.awt.Dimension(48, 32));
        n9.setMinimumSize(new java.awt.Dimension(48, 32));
        n9.setName("9"); // NOI18N
        n9.setPreferredSize(new java.awt.Dimension(48, 32));

        n4.setText("4");
        n4.setMaximumSize(new java.awt.Dimension(48, 32));
        n4.setMinimumSize(new java.awt.Dimension(48, 32));
        n4.setName("4"); // NOI18N
        n4.setPreferredSize(new java.awt.Dimension(48, 32));

        n5.setText("5");
        n5.setMaximumSize(new java.awt.Dimension(48, 32));
        n5.setMinimumSize(new java.awt.Dimension(48, 32));
        n5.setName("5"); // NOI18N
        n5.setPreferredSize(new java.awt.Dimension(48, 32));

        n6.setText("6");
        n6.setMaximumSize(new java.awt.Dimension(48, 32));
        n6.setMinimumSize(new java.awt.Dimension(48, 32));
        n6.setName("6"); // NOI18N
        n6.setPreferredSize(new java.awt.Dimension(48, 32));

        n3.setText("3");
        n3.setMaximumSize(new java.awt.Dimension(48, 32));
        n3.setMinimumSize(new java.awt.Dimension(48, 32));
        n3.setName("3"); // NOI18N
        n3.setPreferredSize(new java.awt.Dimension(48, 32));

        n2.setText("2");
        n2.setMaximumSize(new java.awt.Dimension(48, 32));
        n2.setMinimumSize(new java.awt.Dimension(48, 32));
        n2.setName("2"); // NOI18N
        n2.setPreferredSize(new java.awt.Dimension(48, 32));

        n1.setText("1");
        n1.setMaximumSize(new java.awt.Dimension(48, 32));
        n1.setMinimumSize(new java.awt.Dimension(48, 32));
        n1.setName("1"); // NOI18N
        n1.setPreferredSize(new java.awt.Dimension(48, 32));

        jButton4.setText("+/-");
        jButton4.setMaximumSize(new java.awt.Dimension(48, 32));
        jButton4.setMinimumSize(new java.awt.Dimension(48, 32));
        jButton4.setPreferredSize(new java.awt.Dimension(48, 32));

        n0.setText("0");
        n0.setMaximumSize(new java.awt.Dimension(48, 32));
        n0.setMinimumSize(new java.awt.Dimension(48, 32));
        n0.setName("0"); // NOI18N
        n0.setPreferredSize(new java.awt.Dimension(48, 32));

        sPunto.setText(".");
        sPunto.setMaximumSize(new java.awt.Dimension(48, 32));
        sPunto.setMinimumSize(new java.awt.Dimension(48, 32));
        sPunto.setName("."); // NOI18N
        sPunto.setPreferredSize(new java.awt.Dimension(48, 32));

        jButton5.setText("C");
        jButton5.setMaximumSize(new java.awt.Dimension(48, 32));
        jButton5.setMinimumSize(new java.awt.Dimension(48, 32));
        jButton5.setPreferredSize(new java.awt.Dimension(48, 32));

        sParentesis.setText("( )");
        sParentesis.setMaximumSize(new java.awt.Dimension(48, 32));
        sParentesis.setMinimumSize(new java.awt.Dimension(48, 32));
        sParentesis.setName("()"); // NOI18N
        sParentesis.setPreferredSize(new java.awt.Dimension(48, 32));

        sPorcentaje.setText("%");
        sPorcentaje.setMaximumSize(new java.awt.Dimension(48, 32));
        sPorcentaje.setMinimumSize(new java.awt.Dimension(48, 32));
        sPorcentaje.setName("%"); // NOI18N
        sPorcentaje.setPreferredSize(new java.awt.Dimension(48, 32));

        sDivision.setText("/");
        sDivision.setMaximumSize(new java.awt.Dimension(48, 32));
        sDivision.setMinimumSize(new java.awt.Dimension(48, 32));
        sDivision.setName("/"); // NOI18N
        sDivision.setPreferredSize(new java.awt.Dimension(48, 32));

        sMultiplicar.setText("*");
        sMultiplicar.setMaximumSize(new java.awt.Dimension(48, 32));
        sMultiplicar.setMinimumSize(new java.awt.Dimension(48, 32));
        sMultiplicar.setName("*"); // NOI18N
        sMultiplicar.setPreferredSize(new java.awt.Dimension(48, 32));

        sRestar.setText("-");
        sRestar.setMaximumSize(new java.awt.Dimension(48, 32));
        sRestar.setMinimumSize(new java.awt.Dimension(48, 32));
        sRestar.setName("-"); // NOI18N
        sRestar.setPreferredSize(new java.awt.Dimension(48, 32));

        sSumar.setText("+");
        sSumar.setMaximumSize(new java.awt.Dimension(48, 32));
        sSumar.setMinimumSize(new java.awt.Dimension(48, 32));
        sSumar.setName("+"); // NOI18N
        sSumar.setPreferredSize(new java.awt.Dimension(48, 32));

        jButton27.setText("=");
        jButton27.setMaximumSize(new java.awt.Dimension(48, 32));
        jButton27.setMinimumSize(new java.awt.Dimension(48, 32));
        jButton27.setPreferredSize(new java.awt.Dimension(48, 32));

        javax.swing.GroupLayout jPanelBasicoLayout = new javax.swing.GroupLayout(jPanelBasico);
        jPanelBasico.setLayout(jPanelBasicoLayout);
        jPanelBasicoLayout.setHorizontalGroup(
            jPanelBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBasicoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sRestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sSumar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanelBasicoLayout.setVerticalGroup(
            jPanelBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBasicoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBasicoLayout.createSequentialGroup()
                        .addComponent(sDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sRestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sSumar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBasicoLayout.createSequentialGroup()
                        .addGroup(jPanelBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        n1.getAccessibleContext().setAccessibleName("n1");

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(64, 46));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(64, 46));
        jMenuBar1.setRequestFocusEnabled(false);

        jMenu1.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setLabel("ALGORITMO");
        jMenu1.setMargin(new java.awt.Insets(0, 2, 0, 2));
        jMenu1.setMinimumSize(new java.awt.Dimension(69, 25));
        jMenu1.setPreferredSize(new java.awt.Dimension(79, 25));

        jMenuItem1.setText("Newthon Rapshon");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelBasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBasico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanelBasico;
    public static javax.swing.JPanel jPanelFn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField jTextFieldEcuacion;
    public static javax.swing.JButton n0;
    public static javax.swing.JButton n1;
    public static javax.swing.JButton n2;
    public static javax.swing.JButton n3;
    public static javax.swing.JButton n4;
    public static javax.swing.JButton n5;
    public static javax.swing.JButton n6;
    public static javax.swing.JButton n7;
    public static javax.swing.JButton n8;
    public static javax.swing.JButton n9;
    public static javax.swing.JButton sCoseno;
    public static javax.swing.JButton sDivision;
    public static javax.swing.JButton sElevacion2;
    public static javax.swing.JButton sElevacionY;
    public static javax.swing.JButton sExponencial;
    public static javax.swing.JButton sExponencialX;
    public static javax.swing.JButton sInverso;
    public static javax.swing.JButton sLog;
    public static javax.swing.JButton sLogNatural;
    public static javax.swing.JButton sMultiplicar;
    public static javax.swing.JButton sNotacion;
    public static javax.swing.JButton sPI;
    public static javax.swing.JButton sParentesis;
    public static javax.swing.JButton sPorcentaje;
    public static javax.swing.JButton sPunto;
    private javax.swing.JButton sRadianes;
    public static javax.swing.JButton sRaiz;
    public static javax.swing.JButton sRestar;
    public static javax.swing.JButton sSeno;
    public static javax.swing.JButton sSumar;
    public static javax.swing.JButton sTangente;
    public static javax.swing.JButton sValorAbs;
    // End of variables declaration//GEN-END:variables
}
